# .bash_profile

test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

stty -ixon
shopt -s autocd

export PROMPT_COMMAND="history -a; history -n"
export HISTIGNORE='clear*:_home*:exit:pwd'

PS1="\n\[\e[38;5;223m\]\u@\h \[\e[38;5;203m\]\$PWD\[\e[38;5;195m\]\$(_ps1_branch)\n\[\e[38;5;195m\]$\[\e[0;0m\] "
