set rnu
set nu
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab
set autoindent
set smartindent
set hlsearch
set termguicolors
set mouse=a

syntax on

colorscheme wildcharm
"colorscheme elflord

if has('autocmd')
   autocmd Filetype makefile setlocal noexpandtab
   autocmd FileType xml setlocal indentexpr=
   autocmd BufWritePre * :%s/\(\s*\n\)\+\%$//ge
   autocmd BufWritePre * :%s/\(\s*\n\)\{3,}/\r\r/ge
   autocmd BufWritePre *\(.md\)\@<! :%s/\s\+$//e
endif

nnoremap ,c :nohlsearch<CR>
nnoremap ,i mqggVG=`qzz
nnoremap ,b :e ++ff=unix<CR>
nnoremap ,m :%s/\r$//<CR>
nnoremap ,s :set ft=sh<CR>
nnoremap ,d ciW"<C-r>""<Esc>
nnoremap ," va':s/\%V'/"/g<CR>
nnoremap ,' va":s/\%V"/'/g<CR>
nnoremap ,D 0f=bywoecho "debug: <C-r>" $<C-r>""<Esc>
nnoremap ,v 0f=byw
nnoremap ,q A"<Esc>F=a"<Esc>
nnoremap ,Q A'<Esc>F=a'<Esc>
nnoremap ,l viwgu
nnoremap ,u viwgU
