# .bash_aliases

# General
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias grep='grep --color=auto'
alias ls='eza'
alias lst='ls -lhs newest --group-directories-first --icons=auto'
alias lstd='lst -D'
alias lat='lst -a'
alias newf='ls -fs newest | tail -1'
alias newd='ls -Ds newest | tail -1'
alias newest='ls -s newest | tail -1'
alias rp='realpath'
alias vi='vim -b'

# System
alias pacman='sudo pacman'
alias rmpkg='sudo pacman -Rsn'
alias cleanch='sudo pacman -Scc'
alias fixpacman='sudo rm /var/lib/pacman/db.lck'
alias update='sudo pacman -Syu'
alias cleanup='sudo pacman -Rsn $(pacman -Qtdq)' # Cleanup orphaned packages
alias rip='expac --timefmt="%Y-%m-%d %T" "%l\t%n %v" | sort | tail -200 | nl' # Recent installed packages

# Workspaces
alias work='_tmux_window work'
alias bin='_tmux_window bin'
alias scripts='_tmux_window scripts'
alias dotfiles='_tmux_window dotfiles'

# Scripts
alias newsh='new_script.sh'
alias newws='setup_workspace.sh'
alias vgrep='visual_grep.sh'
alias explore='explore.sh'
alias sw='split_window.sh'

# Functions
alias notes='_notes'
alias exit='_exit'
alias al='_alias_lookup'
alias fvim='_fzf_vim'
alias espa='_enable_sshd_password_auth'
alias fud='_fzf_unmounted_device'
alias cbu='_create_bootable_usb'

# Tmux
alias detach='_detach_tmux_client'

# Git
alias gpull='_git_pull'
alias gpush='_git_push'
alias gclean='_git_clean'
alias gdn='_gen_dev_note'
alias gbs='_git_branch_selector'
alias gl='git log --pretty=oneline'
alias gll='git log -1 --pretty=oneline'
