# .bash_aliases

# General
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias lat='ls -lat'
alias lst='ls -lt'
alias lstd='ls -ltd'
alias newest='ls -t | head -1'
alias rp='realpath'
alias vi='vim -b'

# System
alias pacman='sudo pacman'
alias rmpkg='sudo pacman -Rsn'
alias cleanch='sudo pacman -Scc'
alias fixpacman='sudo rm /var/lib/pacman/db.lck'
alias update='sudo pacman -Syu'
alias cleanup='sudo pacman -Rsn $(pacman -Qtdq)' # Cleanup orphaned packages
alias rip='expac --timefmt="%Y-%m-%d %T" "%l\t%n %v" | sort | tail -200 | nl' # Recent installed packages

# Workspaces
alias work='_tmux_window work'
alias bin='_tmux_window bin'
alias scripts='_tmux_window scripts'
alias dotfiles='_tmux_window dotfiles'

# Remotes
alias mini='ssh -q R-Mini-s'

# Scripts
alias newsh='new_script.sh'
alias newws='setup_workspace.sh'
alias vgrep='visual_grep.sh'
alias explore='explore.sh'
alias sw='split_window.sh'

# Functions
alias exit='_exit'
alias al='_alias_lookup'
alias fvim='_fzf_vim'
alias minip='_update_ssh_ip R-Mini-s'

# Tmux
alias detach='_detach_tmux_client'

# Git
alias gpull='_git_pull'
alias gpush='_git_push'
alias gclean='_git_clean'
alias gdn='_gen_dev_note'
alias gbs='_git_branch_selector'
alias gl='git log --pretty=oneline'
alias gll='git log -1 --pretty=oneline'
