# .bash_aliases

# General
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias lat='ls -lat'
alias lst='ls -lt'
alias lstd='ls -ltd'
alias rp='realpath'
alias vi='vim -b'

# Workspaces
alias work='_tmux_window work'
alias bin='_tmux_window bin'
alias scripts='_tmux_window scripts'
alias dotfiles='_tmux_window dotfiles'

# Scripts
alias newsh='new_script.sh'
alias newws='setup_workspace.sh'
alias vgrep='visual_grep.sh'
alias explore='explore.sh'

# Remotes
alias mini='ssh R-Mini-s'

# Functions
alias al='_alias_lookup'
alias fvim='_fzf_vim'
alias gpull='_git_pull'
alias gpush='_git_push'
alias gclean='_git_clean'
alias gdn='_gen_dev_note'
alias gbs='_git_branch_selector'
alias minip='_update_ssh_ip R-Mini-s'

# Git
alias gl='git log --pretty=oneline'
alias gll='git log -1 --pretty=oneline'
