# .bashrc

# Source global definitions
test -f /etc/bashrc && . /etc/bashrc

declare -A workspaces

# Set up fzf key bindings and fuzzy completion
eval "$(fzf --bash)"

test -f ~/.bash_functions && . ~/.bash_functions
test -f ~/.bash_aliases && . ~/.bash_aliases
